### ISSUE TITLE
Тема 3 / Циклы for и while / task11

### ISSUE THREAD

**Issue by slavikfish03** [aeksei/DD-PY-1-issue#11]
В решении к данному заданию вероятно допущена ошибка:
while num != 1:
____if num % 2 == 1:
________num *= 3
________num += 1
____num //= 2
____count += 1

После блока условия полученное число number **всегда** делится на 2, а должно только если является четным

При проверке чисел 27 и 19 получается ответ 70 и 14 соответственно, что неверно -- от 27 к 1 можно прийти за 111 шагов, от 19 к 1 за 20 шагов (источник: https://ru.wikipedia.org/wiki/Гипотеза_Коллатца)

**Comment by aeksei** [comment]
@slavikfish03 Спасибо большое за уточнение!
Исправлено в новой версии
