### ISSUE TITLE
Тема 2 / Лабораторные работы #4

### ISSUE THREAD

**Issue by Sblrok03** [aeksei/DD-PY-1-issue#14]
Почему при подстановке и выведении list_numbers[4] получаются разные числа? (-17,45 и -16,5225)
![задание1](https://user-images.githubusercontent.com/115463151/197331332-c4a2f1db-0a76-4981-a5a6-0b9c44a5ff16.png)

**Comment by Egowkins** [comment]
Потому что сначала ты присвоил значение элементу, т.е. -36 у тебя заменилось на -16.5225. А потом ты уже работал с измененным списком

**Comment by Sblrok03** [comment]
> Потому что сначала ты присвоил значение элементу, т.е. -36 у тебя заменилось на -16.5225. А потом ты уже работал с измененным списком

Точно! Спасибо большое)
