### ISSUE TITLE
Тема 5 lambda функции task 5

### ISSUE THREAD

**Issue by AntipinMS** [aeksei/DD-PY-1-issue#16]
![image](https://user-images.githubusercontent.com/115109119/198060708-ac8a6dd4-021e-479f-8a5d-79c6a6d8deef.png)
Что значит алфавитный порядок?

**Comment by aeksei** [comment]
@AntipinMS Словари в списке должны быть отсортированы по полю `name`.
В исходнике задания и ошибка. В ответе тоже ошибка(

Спасибо, исправим!

**Comment by aeksei** [comment]
Исправлено в новой версии
