### ISSUE TITLE
Лабораторная работа 4/task2

### ISSUE THREAD

**Issue by AntipinMS** [aeksei/DD-PY-1-issue#18]
Написал код, решил не скидывать(если надо, могу).
Если я напишу print(get_count_char(main_str)) (то есть выведу словарь, где каждому ключу соответствует КОЛИЧЕСТВО, а не ПРОЦЕНТНОЕ СООТНОШЕНИЕ), то EduTools принимает ответ.
Если я напишу print(frequency(get_count_char(main_str))) (то есть выведу словарь, где каждому ключу соответствует  ПРОЦЕНТНОЕ СООТНОШЕНИЕ), то выдает ошибку.
Проверьте корректность формулировки задания или корректность нужного ответа.

**Comment by aeksei** [comment]
Формально, что описано в задании не противоречит ответу :) 
Для ответа надо вывести `print(get_count_char(main_str))`. Это уже написано. 
5 пункт просит написать функцию, но вызывать для проверки он не просит)

Но уточнения сделаем. Спасибо

**Comment by aeksei** [comment]
Исправлено в новой версии
