### ISSUE TITLE
Тема 5, глава "Встроенные модули", задание 3 - в ответе опечатка.

### ISSUE THREAD

**Issue by Mihanakis** [aeksei/DD-PY-1-issue#23]
В решении 20 чисел, в задании 50. На ответ не влияет, так как там random и не проверить - но опечатка.
![image](https://user-images.githubusercontent.com/115340358/200333572-28fafe7d-383a-4b5e-8df6-a0bdcfb354a0.png)

**Comment by aeksei** [comment]
@Mihanakis Спасибо за уточнение!
Исправлено в новой версии
